package mirror

// `interval` as Arrow MonthDayNano.
//
// docs/23 mapped four temporal types to Arrow and left this one as text,
// calling it "a gap, not a refusal". The refusal next to it is `time with time
// zone`, which genuinely has no Arrow equivalent — an offset without a date is
// not a point on any timeline. `interval` is different: Arrow has exactly the
// right type. It was left out because the plumbing carried one int64 per value
// and a MonthDayNano is three fields, so adding it meant widening a path rather
// than adding a case.
//
// The cost of leaving it was the same one docs/23 fixed for timestamps: a query
// written against the source does not run against the mirror. `WHERE d >
// interval '1 hour'` does not compare durations to a VARCHAR, it fails to plan.
//
// THREE FIELDS, NOT ONE NUMBER. Months, days and microseconds are independent
// and cannot be collapsed: a month is 28, 29, 30 or 31 days depending on which
// month, and a day is 23, 24 or 25 hours across a DST boundary. PostgreSQL
// stores all three separately for that reason and so does this.
//
// The rendering is the hard part, and it was not derived by reading the
// documentation. It is checked against 317 intervals generated by PostgreSQL 17
// itself (testdata/interval_golden.tsv), because the format has rules that look
// like bugs until you see enough of them:
//
//	1 year 3 mons 19 days -04:23:45.536088     a negative part among positives
//	-1 years -4 mons +10 days -12:54:21.024382 an explicit + on a positive part
//	-5 mons +12 days 03:46:59.379269           ...but NOT on the time here
//	-1 years                                   plural, because -1 != 1
//
// The sign rule is: a part prints an explicit `+` when it is positive and the
// part IMMEDIATELY BEFORE IT was negative. Not "any earlier part" — that is the
// rule that gets the third line above wrong.

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/apache/arrow-go/v18/arrow"
)

const microsPerSecond = 1_000_000

// renderInterval writes the text PostgreSQL would print for this interval under
// IntervalStyle=postgres, which internal/pgtext pins on every connection.
func renderInterval(v arrow.MonthDayNanoInterval) string {
	years, mons := int(v.Months)/12, int(v.Months)%12
	days := int(v.Days)
	micros := v.Nanoseconds / 1000

	var parts []string
	prevNegative := false
	emitted := false

	unit := func(n int, singular string) {
		if n == 0 {
			return
		}
		name := singular
		if n != 1 {
			// Plural on anything that is not exactly 1, which includes -1:
			// PostgreSQL prints "-1 years", not "-1 year".
			name += "s"
		}
		sign := ""
		if emitted && prevNegative && n > 0 {
			sign = "+"
		}
		parts = append(parts, fmt.Sprintf("%s%d %s", sign, n, name))
		prevNegative = n < 0
		emitted = true
	}

	unit(years, "year")
	unit(mons, "mon")
	unit(days, "day")

	// The time is emitted when it is non-zero, or when nothing else was — a
	// zero interval is "00:00:00", not the empty string.
	if micros != 0 || !emitted {
		sign := ""
		if micros < 0 {
			sign = "-"
			micros = -micros
		} else if emitted && prevNegative {
			sign = "+"
		}
		h := micros / (3600 * microsPerSecond)
		m := micros / (60 * microsPerSecond) % 60
		s := micros / microsPerSecond % 60
		frac := micros % microsPerSecond
		t := fmt.Sprintf("%s%02d:%02d:%02d", sign, h, m, s)
		if frac != 0 {
			// Trailing zeros are trimmed: PostgreSQL prints .51325, not
			// .513250, and the mirror's text has to match the source's or
			// every row reads as a divergence.
			t += "." + strings.TrimRight(fmt.Sprintf("%06d", frac), "0")
		}
		parts = append(parts, t)
	}
	return strings.Join(parts, " ")
}

// parseInterval reads PostgreSQL's postgres-style interval text back into the
// three fields. It is the exact inverse of renderInterval, and the golden test
// checks that round trip on every row of the corpus.
func parseInterval(s string) (arrow.MonthDayNanoInterval, bool) {
	var out arrow.MonthDayNanoInterval
	fields := strings.Fields(strings.TrimSpace(s))
	if len(fields) == 0 {
		return out, false
	}

	months, days := 0, 0
	var micros int64

	// Fields alternate <count> <unit>, with an optional clock last. Anything
	// else is not this format, and guessing at a value that does not parse is
	// how a wrong duration reaches the mirror looking right.
	for i := 0; i < len(fields); i++ {
		if strings.Contains(fields[i], ":") {
			us, ok := parseIntervalClock(fields[i])
			if !ok {
				return out, false
			}
			micros = us
			continue
		}
		if i+1 >= len(fields) {
			return out, false
		}
		n, err := strconv.Atoi(strings.TrimPrefix(fields[i], "+"))
		if err != nil {
			return out, false
		}
		switch strings.TrimSuffix(fields[i+1], "s") {
		case "year":
			months += n * 12
		case "mon":
			months += n
		case "day":
			days += n
		default:
			return out, false
		}
		i++
	}

	out.Months = int32(months)
	out.Days = int32(days)
	out.Nanoseconds = micros * 1000
	return out, true
}

// parseIntervalClock reads [-]HH:MM:SS[.ffffff] into microseconds. Hours are
// not bounded at 24: `interval '100:00:00'` is legal and means 100 hours.
func parseIntervalClock(f string) (int64, bool) {
	neg := false
	switch f[0] {
	case '-':
		neg, f = true, f[1:]
	case '+':
		f = f[1:]
	}
	hh, mm, rest := "", "", ""
	p := strings.Split(f, ":")
	if len(p) != 3 {
		return 0, false
	}
	hh, mm, rest = p[0], p[1], p[2]

	sec, frac := rest, ""
	if i := strings.Index(rest, "."); i >= 0 {
		sec, frac = rest[:i], rest[i+1:]
	}
	h, err1 := strconv.ParseInt(hh, 10, 64)
	m, err2 := strconv.ParseInt(mm, 10, 64)
	sc, err3 := strconv.ParseInt(sec, 10, 64)
	if err1 != nil || err2 != nil || err3 != nil {
		return 0, false
	}
	us := int64(0)
	if frac != "" {
		// Right-pad to six digits: ".5" is 500000 microseconds, not 5.
		for len(frac) < 6 {
			frac += "0"
		}
		if len(frac) > 6 {
			frac = frac[:6]
		}
		v, err := strconv.ParseInt(frac, 10, 64)
		if err != nil {
			return 0, false
		}
		us = v
	}
	total := h*3600*microsPerSecond + m*60*microsPerSecond + sc*microsPerSecond + us
	if neg {
		total = -total
	}
	return total, true
}
