package mirror

// The oracle is PostgreSQL, not my reading of its documentation.
//
// testdata/interval_golden.tsv is 317 intervals generated by PostgreSQL 17
// under IntervalStyle=postgres — the style internal/pgtext pins on every
// connection — each as (months, days, microseconds, text). The renderer has to
// reproduce that text exactly, because the text is what the checksum compares
// and what a reader of the mirror sees. A renderer that is merely plausible
// makes every row of an interval column read as a divergence.
//
// Regenerate with:
//
//	psql -Atc "SET IntervalStyle='postgres';
//	  SELECT (extract(year from v)*12 + extract(month from v))::bigint || E'\t' ||
//	         extract(day from v)::bigint || E'\t' ||
//	         round((extract(hour from v)*3600 + extract(minute from v)*60 +
//	                extract(second from v)) * 1000000)::bigint || E'\t' || v::text
//	  FROM (...) t"

import (
	"bufio"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
	"github.com/apache/arrow-go/v18/parquet"
	"github.com/apache/arrow-go/v18/parquet/pqarrow"
)

func TestIntervalMatchesPostgres(t *testing.T) {
	f, err := os.Open("testdata/interval_golden.tsv")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	n, renderFails, roundTripFails := 0, 0, 0
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.TrimSpace(line) == "" {
			continue
		}
		p := strings.Split(line, "\t")
		if len(p) != 4 {
			t.Fatalf("malformed golden row: %q", line)
		}
		months, _ := strconv.ParseInt(p[0], 10, 32)
		days, _ := strconv.ParseInt(p[1], 10, 32)
		micros, _ := strconv.ParseInt(p[2], 10, 64)
		want := p[3]
		n++

		iv := arrow.MonthDayNanoInterval{
			Months:      int32(months),
			Days:        int32(days),
			Nanoseconds: micros * 1000,
		}

		if got := renderInterval(iv); got != want {
			if renderFails < 8 {
				t.Errorf("render(%d mons, %d days, %d us)\n  got  %q\n  want %q",
					months, days, micros, got, want)
			}
			renderFails++
			continue
		}

		// And back. pgoutput delivers this text, so a value the mirror cannot
		// read back is one it cannot store.
		back, ok := parseInterval(want)
		if !ok {
			if roundTripFails < 8 {
				t.Errorf("parse(%q) refused the text PostgreSQL printed", want)
			}
			roundTripFails++
			continue
		}
		if back != iv {
			if roundTripFails < 8 {
				t.Errorf("round trip of %q: got %+v, want %+v", want, back, iv)
			}
			roundTripFails++
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	if n < 100 {
		t.Fatalf("the golden corpus has only %d rows; it is meant to be large "+
			"enough that the sign and plural rules cannot pass by luck", n)
	}
	t.Logf("%d intervals, %d render failures, %d round-trip failures",
		n, renderFails, roundTripFails)
}

// The cases that read like bugs until you have seen enough of them, named so a
// failure says which rule broke rather than just printing two strings.
func TestIntervalFormattingRules(t *testing.T) {
	us := func(h, m, s int64, frac int64) int64 {
		return ((h*3600+m*60+s)*microsPerSecond + frac) * 1000
	}
	for _, c := range []struct {
		name       string
		mons, days int32
		nanos      int64
		want       string
	}{
		{"zero is a clock, not empty", 0, 0, 0, "00:00:00"},
		{"singular at exactly one", 12, 0, 0, "1 year"},
		{"plural at minus one, because -1 != 1", -12, 0, 0, "-1 years"},
		{"months roll into years", 13, 0, 0, "1 year 1 mon"},
		{"a negative part among positives", 15, 19, -us(4, 23, 45, 536088), "1 year 3 mons 19 days -04:23:45.536088"},
		{"explicit + after a negative part", -16, 10, -us(12, 54, 21, 24382), "-1 years -4 mons +10 days -12:54:21.024382"},
		{"but NOT when the part before it was positive", -5, 12, us(3, 46, 59, 379269), "-5 mons +12 days 03:46:59.379269"},
		{"fractions keep their leading zeros", 0, 0, us(0, 0, 0, 123456), "00:00:00.123456"},
		{"fractions lose their trailing zeros", 0, 0, us(0, 0, 0, 51325) * 10, "00:00:00.51325"},
		{"hours are not bounded at 24", 0, 0, us(100, 0, 0, 0), "100:00:00"},
	} {
		t.Run(c.name, func(t *testing.T) {
			iv := arrow.MonthDayNanoInterval{Months: c.mons, Days: c.days, Nanoseconds: c.nanos}
			if got := renderInterval(iv); got != c.want {
				t.Errorf("got %q, want %q", got, c.want)
			}
			if back, ok := parseInterval(c.want); !ok || back != iv {
				t.Errorf("round trip of %q: %+v ok=%v, want %+v", c.want, back, ok, iv)
			}
		})
	}
}

// Why interval is NOT stored as a duration, asserted so the reasons stay true.
//
// Each of the three blockers below is checkable, and if any stops being true
// the storage change becomes worth making. A comment saying "blocked" rots; a
// test saying "blocked, and here is the check" tells you when it is not.
func TestIntervalStaysTextForMeasuredReasons(t *testing.T) {
	// 1. arrow-go's Parquet writer does not implement MonthDayNanoInterval.
	//    The type exists in Arrow and appears in pqarrow's schema TEST, not in
	//    its writer, so asking for it fails at Write time rather than at
	//    schema construction — which is why this probes a real write.
	dir := t.TempDir()
	schema := arrow.NewSchema([]arrow.Field{
		{Name: "d", Type: arrow.FixedWidthTypes.MonthDayNanoInterval, Nullable: true},
	}, nil)
	f, err := os.Create(filepath.Join(dir, "probe.parquet"))
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	//    A refusal at CONSTRUCTION is the blocker just as much as one at Write,
	//    so it is recorded and the remaining checks still run. Skipping here
	//    would leave blockers 2 and 3 unasserted on exactly the builds where
	//    blocker 1 holds.
	var werr error
	w, err := pqarrow.NewFileWriter(schema, f, parquet.NewWriterProperties(),
		pqarrow.DefaultWriterProps())
	if err != nil {
		werr = err
		t.Logf("blocker 1 confirmed at writer construction: %v", err)
	} else {
		b := array.NewMonthDayNanoIntervalBuilder(memory.DefaultAllocator)
		b.Append(arrow.MonthDayNanoInterval{Months: 15, Days: 19, Nanoseconds: -15825536088000})
		arr := b.NewArray()
		rec := array.NewRecord(schema, []arrow.Array{arr}, 1)
		werr = w.Write(rec)
		_ = w.Close()
		if werr != nil {
			t.Logf("blocker 1 confirmed at write: %v", werr)
		}
	}
	if werr == nil {
		t.Error("arrow-go now writes MonthDayNanoInterval to Parquet. That removes " +
			"blocker 1 of 3 — but not blocker 2: Parquet's INTERVAL logical type " +
			"is (months, days, MILLIseconds), so it still cannot hold PostgreSQL's " +
			"microseconds. See interval.go.")
	}

	// 2. interval is therefore still text, and arrowType must agree with that
	//    rather than asking for a type nothing can write.
	if temporalOf("interval") != notTemporal {
		t.Error("interval is classified as temporal, so arrowType will ask for " +
			"an Arrow type the Parquet writer refuses")
	}
	if got := arrowType("interval"); got != arrow.BinaryTypes.String {
		t.Errorf("arrowType(interval) = %v, want String — interval is stored as "+
			"text until the blockers in interval.go are gone", got)
	}
}
